export const PUT    = 'ACTIONIZER.COMMAND.PUT';
export const CALL   = 'ACTIONIZER.COMMAND.CALL';
export const FORK   = 'ACTIONIZER.COMMAND.FORK';
export const CANCEL = 'ACTIONIZER.COMMAND.CANCEL';
export const SELECT = 'ACTIONIZER.COMMAND.SELECT';
